---
language: php

addons:
  apt:
    packages:
    - moreutils # pee

cache:
  directories:
  - $HOME/.composer/cache/files


install:
- composer require symfony/form:3.3.12
- |
  install --directory negative
  cd negative
  composer init
  composer require symfony/http-foundation


script:
# This checks that the application doesn't use dependencies with known security vulnerabilities
- |
  curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock | pee 'grep "No known\* vulnerabilities detected." > /dev/null' cat

- |
  curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@../composer.lock | pee '! grep "No known\* vulnerabilities detected." > /dev/null' cat
  # With a negation to succeed when security vulnerabilities are found.
